[build-system]
requires = ["setuptools>=81.0.0", "wheel>=0.46.0"]
build-backend = "setuptools.build_meta"

[project]
name = "information-beb48618-576e-45ea-bd50-9e47279f88dc"
version = "0.0.0"
requires-python = ">=3.12.0"
description = "Personal Markdown knowledge base"
dependencies = [
  "aiohttp>=3.9.0",
  "aioshutil>=1.2.0",
  "anyio>=3.6.0",
  "asyncstdlib>=3.10.0",
  "beautifulsoup4>=4.12.0",
  "cihai>=0.18.0",
  "country-converter>=1.3.0",
  "jaraco.clipboard>=3.1.0",
  "markdown>=3.6.0",
  "numpy>=2.0.0",
  "pyperclip>=1.9.0",
  "pytextgen>=6.3.0",
  "pyyaml>=6.0.0",
  "typing_extensions>=4.4.0",
  "yarl>=1.9.0",
]

[dependency-groups]
dev = [
  "black>=26.1.0",
  "hypothesis>=6.151.0",
  "isort>=7.0.0",
  "pytest>=9.0.0",
  "pytest-asyncio>=1.3.0",
  "pytest-cov>=7.0.0",
  "pytest-xdist>=3.8.0",
  "ruff>=0.15.0",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = ["--cov=./", "--dist=loadscope", "-n=auto", "--strict-markers"]
testpaths = ["tests"]
python_files = "test_*.py"

[tool.ruff]
line-length = 88

[tool.setuptools]
packages = []
